// Catalog mirrored from the database and Master Country & Programs Plan 2026. Bilingual EN/AR.
import bulgaria from "@/assets/pics/bulgaria.jpeg";
import luxembourg from "@/assets/pics/luxmberg.jpeg";
import armenia from "@/assets/pics/armeina.jpeg";
import russia from "@/assets/pics/russia.jpeg";
import italy from "@/assets/pics/italy.jpeg";
import slovenia from "@/assets/pics/solvenia.jpeg";
import ireland from "@/assets/pics/ireland.jpeg";

export type Track = "student" | "graduate";
export type Program = {
  slug: string;
  track: Track;
  title: string;
  titleAr: string;
  category: string;
  categoryAr: string;
  duration: string;           // display string e.g. "3–6 months"
  durationOptions?: string[]; // selectable options e.g. ["3 months","4 months"]
  price: number;              // EUR — total cost
  deposit: number;            // EUR — upfront deposit
  installments: number;       // max installment count
  flightPrice?: number;       // EUR added when flight included (0 = no flight option)
  expectedSalary?: string;
  expectedSalaryAr?: string;
  workingHours?: string;
  accommodation?: string;
  accommodationAr?: string;
  requirements?: string[];
  requirementsAr?: string[];
};

export type Country = {
  slug: string;
  name: string;
  nameAr: string;
  flag: string;
  image: string;
  tagline: string;
  taglineAr: string;
  description: string;
  descriptionAr: string;
  programs: Program[];
  documents: string[];
  eligibility: string[];
  timeline: { step: string; time: string }[];
};

export const MAX_INSTALLMENTS = 6;

// ─── Pricing Rules ────────────────────────────────────────────────────────────
// EGP/EUR rate: 54 EGP per 1 EUR
// Student total: max 35,000 EGP ≈ max 648 EUR
// Deposit: 10,000–12,000 EGP ≈ 185–222 EUR (unchanged)
// Flight option: 10,000–12,000 EGP (185–222 EUR) for most countries
//                15,000 EGP (278 EUR) for Ireland only (most expensive)
// ─── Duration Rules ───────────────────────────────────────────────────────────
// Students:  3, 4, 5, 6 months
// Graduates: 9, 12, 15, 18, 24 months
export const STUDENT_DURATION_OPTIONS  = ["3 months", "4 months", "5 months", "6 months"];
export const GRADUATE_DURATION_OPTIONS = ["9 months", "12 months", "15 months", "18 months", "24 months"];

// Standard flight add-on prices (EUR)
export const FLIGHT_PRICE_STANDARD = 204; // ≈ 11,016 EGP — most countries
export const FLIGHT_PRICE_PREMIUM  = 278; // ≈ 15,012 EGP — Ireland only

const docs = [
  "CV in English (السيرة الذاتية)",
  "Valid passport (12+ months) (جواز سفر سارٍ)",
  "Recent passport photo (صورة شخصية حديثة)",
  "Educational certificate / Student proof (شهادة التخرج أو إثبات قيد)",
  "Medical certificate (شهادة صحية)",
  "Police clearance (صحيفة الحالة الجنائية)",
];

export const countries: Country[] = [
  // ─── BULGARIA ────────────────────────────────────────────────────────────────
  {
    slug: "bulgaria",
    name: "Bulgaria",
    nameAr: "بلغاريا",
    flag: "🇧🇬",
    image: bulgaria,
    tagline: "Seasonal hospitality, logistics & manufacturing on the Black Sea",
    taglineAr: "عمل موسمي في الضيافة واللوجستيات والتصنيع على ساحل البحر الأسود",
    description: "Hotels, resorts, agriculture, and manufacturing along the Black Sea coast recruit international workforce through direct seasonal and multi-year employment contracts with accommodation and visa support.",
    descriptionAr: "توظّف الفنادق والمنتجعات والمصانع في بلغاريا كوادر دولية بعقود موسمية وتوظيف مباشر، مع توفير السكن ودعم إجراءات التصريح والتأشيرة.",
    programs: [
      {
        slug: "bulgaria-student-hospitality",
        track: "student",
        title: "Seasonal Hospitality & Hotel Services",
        titleAr: "عمل موسمي في الضيافة والفنادق (طلاب)",
        category: "Hospitality",
        categoryAr: "ضيافة وفنادق",
        duration: "3–6 months",
        durationOptions: STUDENT_DURATION_OPTIONS,
        price: 610,
        deposit: 196,
        installments: 6,
        flightPrice: FLIGHT_PRICE_STANDARD,
        expectedSalary: "€600–€900 / month",
        expectedSalaryAr: "€600–€900 / شهرياً",
        workingHours: "8 hrs/day · 5–6 days/week",
        accommodation: "Provided by employer",
        accommodationAr: "توفرها جهة العمل",
        requirements: ["Age 18–35", "Basic English", "University enrollment proof"],
        requirementsAr: ["العمر 18–35", "إنجليزية بسيطة", "إثبات قيد الدراسة"],
      },
      {
        slug: "bulgaria-student-resort",
        track: "student",
        title: "Seasonal Beach Resort & Guest Services",
        titleAr: "عمل موسمي في المنتجعات الشاطئية (طلاب)",
        category: "Tourism & Resorts",
        categoryAr: "سياحة ومنتجعات",
        duration: "3–6 months",
        durationOptions: STUDENT_DURATION_OPTIONS,
        price: 620,
        deposit: 196,
        installments: 6,
        flightPrice: FLIGHT_PRICE_STANDARD,
        expectedSalary: "€650–€950 / month",
        expectedSalaryAr: "€650–€950 / شهرياً",
        workingHours: "8 hrs/day · 6 days/week",
        accommodation: "Shared rooms at resort",
        accommodationAr: "غرف مشتركة في المنتجع",
        requirements: ["Age 18–30", "Customer service skills"],
        requirementsAr: ["العمر 18–30", "مهارات خدمة عملاء"],
      },
      {
        slug: "bulgaria-seasonal-agriculture",
        track: "student",
        title: "Seasonal Agriculture & Harvest Work",
        titleAr: "عمل زراعي وحصاد موسمي",
        category: "Agriculture",
        categoryAr: "زراعة وحصاد",
        duration: "3–6 months",
        durationOptions: STUDENT_DURATION_OPTIONS,
        price: 580,
        deposit: 185,
        installments: 6,
        flightPrice: FLIGHT_PRICE_STANDARD,
        expectedSalary: "€500–€750 / month",
        expectedSalaryAr: "€500–€750 / شهرياً",
        workingHours: "6–10 hrs/day · seasonal",
        accommodation: "Farm housing included",
        accommodationAr: "إسكان في المزرعة مشمول",
        requirements: ["Age 18–45", "Physical fitness"],
        requirementsAr: ["العمر 18–45", "لياقة بدنية"],
      },
      {
        slug: "bulgaria-hospitality-worker",
        track: "graduate",
        title: "Hotel & Restaurant Operations",
        titleAr: "عمليات الفنادق والمطاعم (خريجون)",
        category: "Hospitality & F&B",
        categoryAr: "فنادق ومطاعم",
        duration: "9–24 months",
        durationOptions: GRADUATE_DURATION_OPTIONS,
        price: 1850,
        deposit: 204,
        installments: 6,
        flightPrice: FLIGHT_PRICE_STANDARD,
        expectedSalary: "€900–€1,300 / month",
        expectedSalaryAr: "€900–€1,300 / شهرياً",
        workingHours: "8 hrs/day · 5 days/week",
        accommodation: "Staff accommodation available",
        accommodationAr: "سكن موظفين متاح",
        requirements: ["Age 20–40", "Intermediate English or basic Bulgarian", "Hospitality background preferred"],
        requirementsAr: ["العمر 20–40", "إنجليزية متوسطة أو بلغارية بسيطة", "خبرة في الضيافة مفضلة"],
      },
      {
        slug: "bulgaria-logistics-worker",
        track: "graduate",
        title: "Warehouse & Logistics Operations",
        titleAr: "مستودعات وعمليات لوجستية",
        category: "Logistics & Supply Chain",
        categoryAr: "لوجستيات وسلاسل إمداد",
        duration: "9–24 months",
        durationOptions: GRADUATE_DURATION_OPTIONS,
        price: 1800,
        deposit: 204,
        installments: 6,
        flightPrice: FLIGHT_PRICE_STANDARD,
        expectedSalary: "€850–€1,200 / month",
        expectedSalaryAr: "€850–€1,200 / شهرياً",
        workingHours: "8 hrs/day · shift-based",
        accommodation: "Housing allowance provided",
        accommodationAr: "بدل سكن مشمول",
        requirements: ["Age 20–45", "Physical fitness", "Forklift license a plus"],
        requirementsAr: ["العمر 20–45", "لياقة بدنية", "رخصة رافعة شوكية ميزة"],
      },
      {
        slug: "bulgaria-production-worker",
        track: "graduate",
        title: "Manufacturing & Production Line Worker",
        titleAr: "عامل خطوط إنتاج وتصنيع",
        category: "Manufacturing",
        categoryAr: "تصنيع وإنتاج",
        duration: "9–24 months",
        durationOptions: GRADUATE_DURATION_OPTIONS,
        price: 1750,
        deposit: 196,
        installments: 6,
        flightPrice: FLIGHT_PRICE_STANDARD,
        expectedSalary: "€800–€1,100 / month",
        expectedSalaryAr: "€800–€1,100 / شهرياً",
        workingHours: "8 hrs/day · shift rotation",
        accommodation: "Company dormitory",
        accommodationAr: "سكن الشركة",
        requirements: ["Age 20–45", "No specific experience required"],
        requirementsAr: ["العمر 20–45", "لا يشترط خبرة"],
      },
      {
        slug: "bulgaria-skilled-worker",
        track: "graduate",
        title: "Skilled Trades & Technical Professions",
        titleAr: "مهن حرفية وتقنية متخصصة",
        category: "Skilled Trades",
        categoryAr: "حرف ومهن ماهرة",
        duration: "9–24 months",
        durationOptions: GRADUATE_DURATION_OPTIONS,
        price: 2100,
        deposit: 214,
        installments: 6,
        flightPrice: FLIGHT_PRICE_STANDARD,
        expectedSalary: "€1,100–€1,600 / month",
        expectedSalaryAr: "€1,100–€1,600 / شهرياً",
        workingHours: "8 hrs/day · Mon–Fri",
        accommodation: "Allowance or company housing",
        accommodationAr: "بدل سكن أو سكن الشركة",
        requirements: ["Age 21–45", "Technical diploma or trade certificate", "2+ yrs experience"],
        requirementsAr: ["العمر 21–45", "دبلوم فني أو شهادة حرفة", "خبرة سنتين أو أكثر"],
      },
      {
        slug: "bulgaria-nursing-medical-assistant",
        track: "graduate",
        title: "Nurses & Physician Assistants (Hospital & Clinic Care)",
        titleAr: "ممرضون ومساعدو أطباء (رعاية صحية ومستشفيات)",
        category: "Healthcare & Nursing",
        categoryAr: "تمريض ومساعد طبيب",
        duration: "9–24 months",
        durationOptions: GRADUATE_DURATION_OPTIONS,
        price: 1950,
        deposit: 204,
        installments: 6,
        flightPrice: FLIGHT_PRICE_STANDARD,
        expectedSalary: "€1,000–€1,600 / month",
        expectedSalaryAr: "€1,000–€1,600 / شهرياً",
        workingHours: "8 hrs/day · 5 days/week",
        accommodation: "Hospital housing or allowance",
        accommodationAr: "سكن مستشفى أو بدل سكن",
        requirements: ["Nursing / Medical Science diploma or degree", "Basic English", "Medical clearance"],
        requirementsAr: ["مؤهل تمريض أو معهد صحي أو مساعد طبيب", "إنجليزية أساسية", "لياقة طبية"],
      },
      {
        slug: "bulgaria-site-engineers",
        track: "graduate",
        title: "Engineers (Civil, Mechanical & Electrical)",
        titleAr: "مهندسون متخصصون (مدني، ميكانيكا، كهرباء)",
        category: "Engineering",
        categoryAr: "هندسة وتقنية",
        duration: "9–24 months",
        durationOptions: GRADUATE_DURATION_OPTIONS,
        price: 2150,
        deposit: 214,
        installments: 6,
        flightPrice: FLIGHT_PRICE_STANDARD,
        expectedSalary: "€1,200–€1,900 / month",
        expectedSalaryAr: "€1,200–€1,900 / شهرياً",
        workingHours: "8 hrs/day · Mon–Fri",
        accommodation: "Company housing provided",
        accommodationAr: "سكن توفره الشركة",
        requirements: ["BSc in Engineering", "1+ yr experience", "Basic English"],
        requirementsAr: ["بكالوريوس هندسة معتمد", "خبرة سنة أو أكثر", "إنجليزية مقبولة"],
      },
      // Fallbacks
      { slug: "bulgaria-student", track: "student", title: "Student Seasonal Track", titleAr: "مسار الطلاب الموسمي", category: "Students", categoryAr: "طلاب", duration: "3–6 months", durationOptions: STUDENT_DURATION_OPTIONS, price: 610, deposit: 196, installments: 6, flightPrice: FLIGHT_PRICE_STANDARD, expectedSalary: "€600–€900 / month", expectedSalaryAr: "€600–€900 / شهرياً" },
      { slug: "bulgaria-graduate", track: "graduate", title: "Graduate Employment Track", titleAr: "مسار توظيف الخريجين", category: "Graduates", categoryAr: "خريجون", duration: "9–24 months", durationOptions: GRADUATE_DURATION_OPTIONS, price: 1850, deposit: 204, installments: 6, flightPrice: FLIGHT_PRICE_STANDARD, expectedSalary: "€900–€1,300 / month", expectedSalaryAr: "€900–€1,300 / شهرياً" },

    ],
    documents: docs,
    eligibility: ["Age 18–45", "Basic English or Russian", "No prior EU visa refusals", "Valid university enrollment for student tracks"],
    timeline: [
      { step: "Application review & CV screening", time: "2–4 days" },
      { step: "Pre-interview & Employer matching", time: "1–3 weeks" },
      { step: "Work permit issuance", time: "4–8 weeks" },
      { step: "Visa issuance & departure", time: "2–4 weeks" },
    ],
  },

  // ─── LUXEMBOURG ──────────────────────────────────────────────────────────────
  {
    slug: "luxembourg",
    name: "Luxembourg",
    nameAr: "لوكسمبورغ",
    flag: "🇱🇺",
    image: luxembourg,
    tagline: "High-income professional, IT & finance careers in the heart of Europe",
    taglineAr: "وظائف مهنية وتقنية عالية الدخل ودراسة جامعية عليا في قلب أوروبا",
    description: "Skilled positions in IT, logistics, corporate finance, and higher education in one of Europe's strongest economies with regulated work authorization procedures.",
    descriptionAr: "فرص عمل ماهرة في تكنولوجيا المعلومات واللوجستيات والمالية وقبول دراسي في لوكسمبورغ مع إجراءات رسمية معتمدة لتصريح الإقامة والعمل.",
    programs: [
      {
        slug: "luxembourg-higher-education",
        track: "student",
        title: "University Admission & Higher Education",
        titleAr: "قبول ودراسة جامعية عليا",
        category: "Higher Education",
        categoryAr: "تعليم جامعي",
        duration: "Academic year",
        price: 640,
        deposit: 214,
        installments: 6,
        expectedSalary: "Part-time €700–€1,000 / month",
        expectedSalaryAr: "دوام جزئي €700–€1,000 / شهرياً",
        workingHours: "Study full-time + 20 hrs/week work",
        accommodation: "Student housing support",
        accommodationAr: "دعم سكن طلابي",
      },
      {
        slug: "luxembourg-student-parttime",
        track: "student",
        title: "Study & Authorized Part-Time Work",
        titleAr: "دراسة وعمل جزئي مصرح به",
        category: "Education & Work",
        categoryAr: "دراسة وعمل",
        duration: "12 months",
        price: 640,
        deposit: 222,
        installments: 6,
        expectedSalary: "€900–€1,200 / month",
        expectedSalaryAr: "€900–€1,200 / شهرياً",
        workingHours: "20 hrs/week (work) + study",
        accommodation: "Self-arranged or student dorms",
        accommodationAr: "سكن طلابي أو مستقل",
      },
      {
        slug: "luxembourg-skilled-worker",
        track: "graduate",
        title: "Skilled Professional & Specialist Roles",
        titleAr: "وظائف مهنية متخصصة",
        category: "Professional",
        categoryAr: "مهني متخصص",
        duration: "24 months",
        price: 3400,
        deposit: 222,
        installments: 6,
        expectedSalary: "€2,500–€3,800 / month",
        expectedSalaryAr: "€2,500–€3,800 / شهرياً",
        workingHours: "40 hrs/week · Mon–Fri",
        accommodation: "Relocation allowance provided",
        accommodationAr: "بدل انتقال مشمول",
      },
      {
        slug: "luxembourg-it-technology",
        track: "graduate",
        title: "IT, Software Engineering & Tech Roles",
        titleAr: "تكنولوجيا المعلومات وهندسة البرمجيات",
        category: "IT & Technology",
        categoryAr: "تقنية معلومات وبرمجيات",
        duration: "24 months",
        price: 3500,
        deposit: 222,
        installments: 6,
        expectedSalary: "€3,000–€5,000 / month",
        expectedSalaryAr: "€3,000–€5,000 / شهرياً",
        workingHours: "40 hrs/week · flexible",
        accommodation: "Allowance negotiated with employer",
        accommodationAr: "بدل سكن يُحدد مع صاحب العمل",
      },
      {
        slug: "luxembourg-logistics",
        track: "graduate",
        title: "Supply Chain & Logistics Management",
        titleAr: "إدارة سلاسل الإمداد واللوجستيات",
        category: "Logistics & Supply Chain",
        categoryAr: "لوجستيات وسلاسل إمداد",
        duration: "24 months",
        price: 3200,
        deposit: 214,
        installments: 6,
        expectedSalary: "€2,200–€3,200 / month",
        expectedSalaryAr: "€2,200–€3,200 / شهرياً",
        workingHours: "40 hrs/week · shift rotation",
        accommodation: "Housing support available",
        accommodationAr: "دعم السكن متاح",
      },
      {
        slug: "luxembourg-hospitality",
        track: "graduate",
        title: "Fine Dining, Gastronomy & Hotel Operations",
        titleAr: "ضيافة راقية وعمليات فندقية",
        category: "Hospitality & Tourism",
        categoryAr: "ضيافة وسياحة",
        duration: "12–24 months",
        price: 3100,
        deposit: 214,
        installments: 6,
        expectedSalary: "€1,900–€2,700 / month",
        expectedSalaryAr: "€1,900–€2,700 / شهرياً",
        workingHours: "8–9 hrs/day · 5–6 days/week",
        accommodation: "Staff accommodation available",
        accommodationAr: "سكن موظفين متاح",
      },
      {
        slug: "luxembourg-finance",
        track: "graduate",
        title: "Finance, Banking & Accounting",
        titleAr: "المالية والمصرفية والمحاسبة",
        category: "Finance & Banking",
        categoryAr: "مالية ومصرفية",
        duration: "24 months",
        price: 3600,
        deposit: 222,
        installments: 6,
        expectedSalary: "€3,500–€6,000 / month",
        expectedSalaryAr: "€3,500–€6,000 / شهرياً",
        workingHours: "40–45 hrs/week · Mon–Fri",
        accommodation: "Relocation package",
        accommodationAr: "باقة انتقال كاملة",
      },
      {
        slug: "luxembourg-engineering-consultants",
        track: "graduate",
        title: "Senior Engineers & Technical Project Leads",
        titleAr: "مهندسون واستشاريون تقنيون ومشاريع",
        category: "Engineering & Technical",
        categoryAr: "هندسة وتقنية",
        duration: "24 months",
        price: 3600,
        deposit: 222,
        installments: 6,
        expectedSalary: "€3,600–€6,200 / month",
        expectedSalaryAr: "€3,600–€6,200 / شهرياً",
        workingHours: "40 hrs/week · Mon–Fri",
        accommodation: "Relocation package provided",
        accommodationAr: "باقة انتقال وبدل سكن مشمول",
        requirements: ["BSc / MSc in Engineering", "Fluent English or French", "2+ yrs professional experience"],
        requirementsAr: ["بكالوريوس أو ماجستير هندسة", "إنجليزية أو فرنسية ممتازة", "خبرة سنتين أو أكثر"],
      },
      {
        slug: "luxembourg-healthcare-nurses",
        track: "graduate",
        title: "Clinical Nurses & Medical Assistants",
        titleAr: "ممرضون ومساعدو أطباء (رعاية سريرية ومستشفيات)",
        category: "Healthcare & Nursing",
        categoryAr: "تمريض ومساعد طبيب",
        duration: "12–24 months",
        price: 3300,
        deposit: 214,
        installments: 6,
        expectedSalary: "€3,000–€4,800 / month",
        expectedSalaryAr: "€3,000–€4,800 / شهرياً",
        workingHours: "38–40 hrs/week",
        accommodation: "Housing allowance provided",
        accommodationAr: "بدل سكن شهري متاح",
        requirements: ["Nursing / Medical Science degree", "Good English or French", "1+ yr clinical experience"],
        requirementsAr: ["مؤهل تمريض أو علوم طبية", "إنجليزية أو فرنسية جيدة", "خبرة سريرية سنة أو أكثر"],
      },
      // Fallbacks
      { slug: "luxembourg-student", track: "student", title: "Student Track", titleAr: "مسار الطلاب", category: "Students", categoryAr: "طلاب", duration: "Academic year", price: 2800, deposit: 214, installments: 6, expectedSalary: "Part-time €700–€1,000 / month", expectedSalaryAr: "دوام جزئي €700–€1,000 / شهرياً" },
      { slug: "luxembourg-graduate", track: "graduate", title: "Graduate Professional Track", titleAr: "مسار توظيف الخريجين", category: "Graduates", categoryAr: "خريجون", duration: "12–24 months", price: 3200, deposit: 214, installments: 6, expectedSalary: "€2,200–€3,800 / month", expectedSalaryAr: "€2,200–€3,800 / شهرياً" },
    ],
    documents: [...docs, "Academic degrees & translated transcripts (الشهادات المترجمة)"],
    eligibility: ["Age 21–45", "Intermediate English or French", "Relevant academic degree or verifiable work experience"],
    timeline: [
      { step: "Profile assessment & CV refinement", time: "1 week" },
      { step: "Pre-interview & Employer selection", time: "2–4 weeks" },
      { step: "ADEM clearance & permit processing", time: "6–10 weeks" },
      { step: "Visa submission & arrival", time: "2–3 weeks" },
    ],
  },

  // ─── ARMENIA ─────────────────────────────────────────────────────────────────
  {
    slug: "armenia",
    name: "Armenia",
    nameAr: "أرمينيا",
    flag: "🇦🇲",
    image: armenia,
    tagline: "Fast-track work permits & university admissions in Yerevan",
    taglineAr: "فرص عمل سريعة وتصاريح إقامة مرنة وقبول جامعي في يريفان",
    description: "A fast-moving market with accessible work residency, modern electronic permit issuing, and steady demand in services, tech support, manufacturing, and hospitality.",
    descriptionAr: "اقتصاد نامٍ بإجراءات إلكترونية ميسرة وسريعة لتصاريح العمل والإقامة في مجالات الخدمات والتقنية والتصنيع والضيافة.",
    programs: [
      {
        slug: "armenia-university-student",
        track: "student",
        title: "University Admission & Academic Studies",
        titleAr: "قبول جامعي ودراسة أكاديمية",
        category: "Higher Education",
        categoryAr: "تعليم جامعي",
        duration: "Academic year",
        price: 950,
        deposit: 185,
        installments: 6,
        expectedSalary: "Part-time ~€400 / month",
        expectedSalaryAr: "دوام جزئي ~€400 / شهرياً",
        workingHours: "Full-time study + part-time allowed",
        accommodation: "University dorms available",
        accommodationAr: "سكن جامعي متاح",
        requirements: ["Age 17–30", "High school diploma", "English or Russian B1"],
        requirementsAr: ["العمر 17–30", "شهادة ثانوية", "إنجليزية أو روسية B1"],
      },
      {
        slug: "armenia-it-software",
        track: "graduate",
        title: "IT, Web Development & Tech Support",
        titleAr: "تطوير ويب ودعم تقني وتكنولوجيا المعلومات",
        category: "IT & Technology",
        categoryAr: "تقنية معلومات",
        duration: "12–24 months",
        price: 1300,
        deposit: 196,
        installments: 6,
        expectedSalary: "€800–€1,400 / month",
        expectedSalaryAr: "€800–€1,400 / شهرياً",
        workingHours: "40 hrs/week · remote-friendly",
        accommodation: "Apartment allowance negotiable",
        accommodationAr: "بدل شقة قابل للتفاوض",
      },
      {
        slug: "armenia-hospitality",
        track: "graduate",
        title: "Hotel, Tourism & Guest Relations",
        titleAr: "فنادق وسياحة وعلاقات الضيوف",
        category: "Hospitality & Tourism",
        categoryAr: "سياحة وضيافة",
        duration: "12 months",
        price: 1100,
        deposit: 185,
        installments: 6,
        expectedSalary: "€500–€800 / month",
        expectedSalaryAr: "€500–€800 / شهرياً",
        workingHours: "8 hrs/day · 6 days/week",
        accommodation: "Staff housing available",
        accommodationAr: "سكن موظفين متاح",
      },
      {
        slug: "armenia-customer-support",
        track: "graduate",
        title: "Customer Service & Operations Support",
        titleAr: "خدمة عملاء وعمليات تشغيلية",
        category: "Customer Service",
        categoryAr: "خدمة عملاء",
        duration: "12 months",
        price: 1050,
        deposit: 185,
        installments: 6,
        expectedSalary: "€450–€700 / month",
        expectedSalaryAr: "€450–€700 / شهرياً",
        workingHours: "8 hrs/day · shift-based",
        accommodation: "Self-arranged (affordable local market)",
        accommodationAr: "مستقل (سوق محلي معقول)",
      },
      {
        slug: "armenia-manufacturing",
        track: "graduate",
        title: "Industrial Production & Manufacturing",
        titleAr: "عمال إنتاج صناعي وتصنيع",
        category: "Manufacturing",
        categoryAr: "صناعة وتصنيع",
        duration: "12 months",
        price: 1150,
        deposit: 185,
        installments: 6,
        expectedSalary: "€500–€750 / month",
        expectedSalaryAr: "€500–€750 / شهرياً",
        workingHours: "8 hrs/day · 5 days/week",
        accommodation: "Company housing or allowance",
        accommodationAr: "سكن الشركة أو بدل سكن",
      },
      {
        slug: "armenia-logistics",
        track: "graduate",
        title: "Logistics, Warehousing & Freight Dispatch",
        titleAr: "لوجستيات ومستودعات وشحن",
        category: "Logistics",
        categoryAr: "لوجستيات",
        duration: "12 months",
        price: 1150,
        deposit: 185,
        installments: 6,
        expectedSalary: "€550–€800 / month",
        expectedSalaryAr: "€550–€800 / شهرياً",
        workingHours: "8 hrs/day · shift rotation",
        accommodation: "Allowance or warehouse housing",
        accommodationAr: "بدل سكن أو سكن المستودع",
      },
      {
        slug: "armenia-technical-worker",
        track: "graduate",
        title: "Maintenance Technician & Skilled Crafts",
        titleAr: "فنيو صيانة وحرف تقنية ماهرة",
        category: "Technical & Maintenance",
        categoryAr: "فني وصيانة",
        duration: "12 months",
        price: 1250,
        deposit: 196,
        installments: 6,
        expectedSalary: "€700–€1,000 / month",
        expectedSalaryAr: "€700–€1,000 / شهرياً",
        workingHours: "8 hrs/day · Mon–Sat",
        accommodation: "Company arranged",
        accommodationAr: "تُرتبها الشركة",
      },
      // Fallbacks
      { slug: "armenia-student", track: "student", title: "Student Track", titleAr: "مسار الطلاب", category: "Students", categoryAr: "طلاب", duration: "Academic year", price: 950, deposit: 185, installments: 6, expectedSalary: "Part-time ~€400 / month", expectedSalaryAr: "دوام جزئي ~€400 / شهرياً" },
      { slug: "armenia-graduate", track: "graduate", title: "Graduate Employment Track", titleAr: "مسار توظيف الخريجين", category: "Graduates", categoryAr: "خريجون", duration: "12–24 months", price: 1250, deposit: 196, installments: 6, expectedSalary: "€600–€1,000 / month", expectedSalaryAr: "€600–€1,000 / شهرياً" },
    ],
    documents: docs.slice(0, 4),
    eligibility: ["Age 18–50", "Basic English or Russian", "Valid passport"],
    timeline: [
      { step: "Application review & CV check", time: "2–3 days" },
      { step: "Pre-interview & Employer offer", time: "1–2 weeks" },
      { step: "Electronic work permit & visa", time: "2–4 weeks" },
    ],
  },

  // ─── RUSSIA ───────────────────────────────────────────────────────────────────
  {
    slug: "russia",
    name: "Russia",
    nameAr: "روسيا",
    flag: "🇷🇺",
    image: russia,
    tagline: "Industrial, technical & academic opportunities in major cities",
    taglineAr: "برامج عمل صناعية وتقنية ومسارات جامعية في كبرى المدن الروسية",
    description: "Employer sponsorship pathways across industrial production, warehousing, hospitality, and university degree programs in Moscow and major regional capitals.",
    descriptionAr: "مسارات عمل بإشراف أصحاب العمل في مجالات الصناعة واللوجستيات والمطاعم إلى جانب القبول الجامعي والدراسة في موسكو وسانت بطرسبرغ.",
    programs: [
      {
        slug: "russia-university-student",
        track: "student",
        title: "Russian University Admission & Studies",
        titleAr: "قبول جامعي ودراسة في روسيا",
        category: "Higher Education",
        categoryAr: "تعليم جامعي",
        duration: "Academic year",
        price: 1200,
        deposit: 185,
        installments: 6,
        expectedSalary: "Part-time ~€350 / month",
        expectedSalaryAr: "دوام جزئي ~€350 / شهرياً",
        workingHours: "Full-time study",
        accommodation: "University dormitory",
        accommodationAr: "سكن جامعي",
      },
      {
        slug: "russia-student-work",
        track: "student",
        title: "Study & Part-Time Work Pathway",
        titleAr: "مسار الدراسة والعمل الطلابي",
        category: "Education & Work",
        categoryAr: "دراسة وعمل",
        duration: "12 months",
        price: 1350,
        deposit: 196,
        installments: 6,
        expectedSalary: "€400–€650 / month",
        expectedSalaryAr: "€400–€650 / شهرياً",
        workingHours: "20 hrs/week work + study",
        accommodation: "Student housing or company arranged",
        accommodationAr: "سكن طلابي أو تُرتبه الشركة",
      },
      {
        slug: "russia-manufacturing",
        track: "graduate",
        title: "Industrial Factory & Production Work",
        titleAr: "عمال مصانع وإنتاج صناعي",
        category: "Manufacturing & Industry",
        categoryAr: "صناعة وتصنيع",
        duration: "12–24 months",
        price: 1550,
        deposit: 196,
        installments: 6,
        expectedSalary: "€700–€1,100 / month",
        expectedSalaryAr: "€700–€1,100 / شهرياً",
        workingHours: "8 hrs/day · shift-based",
        accommodation: "Factory dormitory",
        accommodationAr: "سكن المصنع",
      },
      {
        slug: "russia-logistics",
        track: "graduate",
        title: "Warehousing & Freight Logistics",
        titleAr: "مستودعات وشحن لوجستي",
        category: "Logistics & Warehousing",
        categoryAr: "لوجستيات ومستودعات",
        duration: "12–24 months",
        price: 1500,
        deposit: 196,
        installments: 6,
        expectedSalary: "€650–€1,000 / month",
        expectedSalaryAr: "€650–€1,000 / شهرياً",
        workingHours: "8 hrs/day · 5–6 days/week",
        accommodation: "Warehouse campus housing",
        accommodationAr: "سكن مجمع المستودع",
      },
      {
        slug: "russia-hospitality",
        track: "graduate",
        title: "Hotel & Restaurant Service Staff",
        titleAr: "موظفو فنادق ومطاعم",
        category: "Hospitality & F&B",
        categoryAr: "ضيافة ومطاعم",
        duration: "12 months",
        price: 1450,
        deposit: 196,
        installments: 6,
        expectedSalary: "€600–€900 / month",
        expectedSalaryAr: "€600–€900 / شهرياً",
        workingHours: "8–10 hrs/day · 5–6 days/week",
        accommodation: "Staff housing available",
        accommodationAr: "سكن موظفين متاح",
      },
      {
        slug: "russia-construction",
        track: "graduate",
        title: "Construction & Civil Site Operations",
        titleAr: "مقاولات وأعمال إنشاءات وبناء",
        category: "Construction & Civil Works",
        categoryAr: "إنشاءات ومقاولات",
        duration: "12–24 months",
        price: 1600,
        deposit: 196,
        installments: 6,
        expectedSalary: "€750–€1,200 / month",
        expectedSalaryAr: "€750–€1,200 / شهرياً",
        workingHours: "10 hrs/day · 5–6 days/week",
        accommodation: "Site camp housing",
        accommodationAr: "سكن موقع البناء",
      },
      {
        slug: "russia-technical-worker",
        track: "graduate",
        title: "Skilled Technicians & Engineering Support",
        titleAr: "فنيون ماهرون ودعم هندسي",
        category: "Technical & Engineering",
        categoryAr: "فني وهندسي",
        duration: "12–24 months",
        price: 1700,
        deposit: 204,
        installments: 6,
        expectedSalary: "€900–€1,400 / month",
        expectedSalaryAr: "€900–€1,400 / شهرياً",
        workingHours: "8 hrs/day · Mon–Fri",
        accommodation: "Company accommodation",
        accommodationAr: "سكن الشركة",
      },
      // Fallbacks
      { slug: "russia-student", track: "student", title: "Student Track", titleAr: "مسار الطلاب", category: "Students", categoryAr: "طلاب", duration: "Academic year", price: 1200, deposit: 185, installments: 6, expectedSalary: "Part-time ~€350 / month", expectedSalaryAr: "دوام جزئي ~€350 / شهرياً" },
      { slug: "russia-graduate", track: "graduate", title: "Graduate Employment Track", titleAr: "مسار توظيف الخريجين", category: "Graduates", categoryAr: "خريجون", duration: "12–24 months", price: 1600, deposit: 196, installments: 6, expectedSalary: "€700–€1,200 / month", expectedSalaryAr: "€700–€1,200 / شهرياً" },
    ],
    documents: docs,
    eligibility: ["Age 18–45", "Basic English (Russian is a plus)", "Clean criminal record"],
    timeline: [
      { step: "Application review & CV check", time: "3–5 days" },
      { step: "Pre-interview & Employer selection", time: "2–3 weeks" },
      { step: "Official invitation letter & work permit", time: "3–5 weeks" },
      { step: "Visa stamping & departure", time: "2–3 weeks" },
    ],
  },

  // ─── ITALY ───────────────────────────────────────────────────────────────────
  {
    slug: "italy",
    name: "Italy",
    nameAr: "إيطاليا",
    flag: "🇮🇹",
    image: italy,
    tagline: "Decreto Flussi quotas in agriculture, hospitality & skilled trades",
    taglineAr: "حصص رسمية (Decreto Flussi) في الزراعة والضيافة والمقاولات والتعليم",
    description: "Official quota employment and student routes across restaurants, agriculture, logistics, and skilled crafts, including nulla osta clearances and direct visa appointment guidance.",
    descriptionAr: "عقود عمل وحصص رسمية معتمدة للزراعة والضيافة والمطاعم والتشييد إلى جانب القبول الجامعي، مع استخراج تصريح النولا أوستا (Nulla Osta).",
    programs: [
      {
        slug: "italy-university-student",
        track: "student",
        title: "University Studies & Higher Education in Italy",
        titleAr: "دراسة جامعية وتعليم عالٍ بإيطاليا",
        category: "Higher Education",
        categoryAr: "تعليم جامعي",
        duration: "Academic year",
        price: 2450,
        deposit: 204,
        installments: 6,
        expectedSalary: "Part-time €600–€900 / month",
        expectedSalaryAr: "دوام جزئي €600–€900 / شهرياً",
        workingHours: "Full-time study + 20 hrs work",
        accommodation: "University housing or private",
        accommodationAr: "سكن جامعي أو خاص",
      },
      {
        slug: "italy-seasonal-agri",
        track: "student",
        title: "Seasonal Agriculture (Decreto Flussi Quota)",
        titleAr: "عمل زراعي موسمي - ضمن الحصص الرسمية",
        category: "Agriculture & Harvest",
        categoryAr: "زراعة وحصاد",
        duration: "6–9 months",
        price: 2300,
        deposit: 204,
        installments: 6,
        expectedSalary: "€900–€1,200 / month",
        expectedSalaryAr: "€900–€1,200 / شهرياً",
        workingHours: "8–10 hrs/day · seasonal",
        accommodation: "Farm accommodation included",
        accommodationAr: "سكن المزرعة مشمول",
      },
      {
        slug: "italy-seasonal-hospitality",
        track: "student",
        title: "Seasonal Coastal & Resort Hospitality",
        titleAr: "ضيافة موسمية في المنتجعات الساحلية",
        category: "Hospitality & Resorts",
        categoryAr: "ضيافة ومنتجعات",
        duration: "6–9 months",
        price: 2400,
        deposit: 204,
        installments: 6,
        expectedSalary: "€1,000–€1,400 / month",
        expectedSalaryAr: "€1,000–€1,400 / شهرياً",
        workingHours: "8–9 hrs/day · 6 days/week",
        accommodation: "Staff lodging at resort",
        accommodationAr: "سكن موظفين في المنتجع",
      },
      {
        slug: "italy-hospitality-general",
        track: "graduate",
        title: "Culinary Arts, Chefs & Restaurant Staff",
        titleAr: "فنون الطهي والطهاة وموظفو المطاعم",
        category: "Culinary & F&B",
        categoryAr: "طهي ومطاعم",
        duration: "12–24 months",
        price: 2850,
        deposit: 214,
        installments: 6,
        expectedSalary: "€1,300–€2,000 / month",
        expectedSalaryAr: "€1,300–€2,000 / شهرياً",
        workingHours: "8 hrs/day · split shifts",
        accommodation: "Staff accommodation or allowance",
        accommodationAr: "سكن موظفين أو بدل سكن",
      },
      {
        slug: "italy-construction",
        track: "graduate",
        title: "Construction, Civil Works & Infrastructure Trades",
        titleAr: "مقاولات وأعمال مدنية وبنية تحتية",
        category: "Construction & Trades",
        categoryAr: "بناء ومقاولات",
        duration: "12–24 months",
        price: 2750,
        deposit: 214,
        installments: 6,
        expectedSalary: "€1,400–€2,200 / month",
        expectedSalaryAr: "€1,400–€2,200 / شهرياً",
        workingHours: "8–10 hrs/day · 5–6 days/week",
        accommodation: "Site housing or allowance",
        accommodationAr: "سكن موقع أو بدل سكن",
      },
      {
        slug: "italy-manufacturing",
        track: "graduate",
        title: "Manufacturing, Industrial & Fabrication Work",
        titleAr: "تصنيع صناعي وخطوط إنتاج",
        category: "Manufacturing",
        categoryAr: "تصنيع وإنتاج",
        duration: "12–24 months",
        price: 2700,
        deposit: 204,
        installments: 6,
        expectedSalary: "€1,300–€1,900 / month",
        expectedSalaryAr: "€1,300–€1,900 / شهرياً",
        workingHours: "8 hrs/day · shift-based",
        accommodation: "Company or local housing",
        accommodationAr: "سكن الشركة أو السوق المحلي",
      },
      {
        slug: "italy-logistics",
        track: "graduate",
        title: "Logistics, Shipping & Freight Operations",
        titleAr: "لوجستيات وشحن ومستودعات",
        category: "Logistics & Freight",
        categoryAr: "لوجستيات وشحن",
        duration: "12–24 months",
        price: 2750,
        deposit: 214,
        installments: 6,
        expectedSalary: "€1,300–€1,900 / month",
        expectedSalaryAr: "€1,300–€1,900 / شهرياً",
        workingHours: "8 hrs/day · shift rotation",
        accommodation: "Allowance provided",
        accommodationAr: "بدل سكن مشمول",
      },
      {
        slug: "italy-skilled-professional",
        track: "graduate",
        title: "Skilled Engineers & Technical Specialists",
        titleAr: "مهندسون وتقنيون متخصصون",
        category: "Engineering & Technical",
        categoryAr: "هندسة وتقنية",
        duration: "24 months",
        price: 3100,
        deposit: 222,
        installments: 6,
        expectedSalary: "€2,200–€3,500 / month",
        expectedSalaryAr: "€2,200–€3,500 / شهرياً",
        workingHours: "40 hrs/week · Mon–Fri",
        accommodation: "Relocation package negotiable",
        accommodationAr: "باقة انتقال قابلة للتفاوض",
      },
      {
        slug: "italy-doctors-physicians",
        track: "graduate",
        title: "Medical Doctors & Healthcare Specialists",
        titleAr: "أطباء بشريون واستشاريو رعاية طبية",
        category: "Healthcare & Medicine",
        categoryAr: "طب ورعاية صحية",
        duration: "12–24 months",
        price: 3300,
        deposit: 222,
        installments: 6,
        expectedSalary: "€3,000–€5,200 / month",
        expectedSalaryAr: "€3,000–€5,200 / شهرياً",
        workingHours: "38–40 hrs/week · Hospital / Clinic",
        accommodation: "Housing allowance provided",
        accommodationAr: "بدل سكن مشمول",
        requirements: ["Medical Degree (MBBCh / MD)", "English or basic Italian", "Medical license eligibility"],
        requirementsAr: ["بكالوريوس طب وجراحة", "إنجليزية أو إيطالية بسيطة", "ترخيص مزاولة المهنة"],
      },
      {
        slug: "italy-nurses-assistants",
        track: "graduate",
        title: "Nurses & Physician Assistants",
        titleAr: "ممرضون ومساعدو أطباء (مستشفيات ومراكز صحية)",
        category: "Healthcare & Nursing",
        categoryAr: "تمريض ومساعد طبيب",
        duration: "12–24 months",
        price: 2950,
        deposit: 214,
        installments: 6,
        expectedSalary: "€1,700–€2,600 / month",
        expectedSalaryAr: "€1,700–€2,600 / شهرياً",
        workingHours: "36–40 hrs/week · Shifts",
        accommodation: "Hospital housing or allowance",
        accommodationAr: "سكن مشفى أو بدل سكن",
        requirements: ["Nursing / Healthcare degree", "Basic Italian or English", "1+ yr experience"],
        requirementsAr: ["مؤهل تمريض أو معهد صحي", "إيطالية بسيطة أو إنجليزية", "خبرة سنة أو أكثر"],
      },
      // Fallbacks
      { slug: "italy-student", track: "student", title: "Student Track", titleAr: "مسار الطلاب", category: "Students", categoryAr: "طلاب", duration: "6–9 months", price: 2450, deposit: 204, installments: 6, expectedSalary: "€600–€900 / month", expectedSalaryAr: "€600–€900 / شهرياً" },
      { slug: "italy-graduate", track: "graduate", title: "Graduate Employment Track", titleAr: "مسار توظيف الخريجين", category: "Graduates", categoryAr: "خريجون", duration: "12–24 months", price: 2850, deposit: 214, installments: 6, expectedSalary: "€1,300–€2,200 / month", expectedSalaryAr: "€1,300–€2,200 / شهرياً" },
    ],
    documents: [...docs, "Work experience certificates (شهادات الخبرة)"],
    eligibility: ["Age 20–45", "Basic English or Italian", "Relevant background in hospitality, crafts or agriculture"],
    timeline: [
      { step: "CV assessment & profile review", time: "1 week" },
      { step: "Pre-interview & employer quota slot", time: "2–4 weeks" },
      { step: "Nulla Osta authorization clearance", time: "6–12 weeks" },
      { step: "Type D visa processing & departure", time: "3–4 weeks" },
    ],
  },

  // ─── SLOVENIA ────────────────────────────────────────────────────────────────
  {
    slug: "slovenia",
    name: "Slovenia",
    nameAr: "سلوفينيا",
    flag: "🇸🇮",
    image: slovenia,
    tagline: "EU single-permit work & tourism jobs in a growing economy",
    taglineAr: "تصاريح عمل أوروبية موحدة في السياحة والصناعة باقتصاد نامٍ",
    description: "An EU member with growing demand for workers in tourism, logistics and manufacturing, and straightforward single-permit procedures.",
    descriptionAr: "دولة عضو في الاتحاد الأوروبي بطلب متزايد على العمالة في السياحة واللوجستيات والتصنيع، بإجراءات تصريح موحدة وواضحة.",
    programs: [
      {
        slug: "slovenia-student",
        track: "student",
        title: "Seasonal Tourism & Hospitality (Students)",
        titleAr: "سياحة وضيافة موسمية للطلاب",
        category: "Tourism & Hospitality",
        categoryAr: "سياحة وضيافة",
        duration: "3–6 months",
        price: 1450,
        deposit: 196,
        installments: 6,
        expectedSalary: "€700–€1,000 / month",
        expectedSalaryAr: "€700–€1,000 / شهرياً",
        workingHours: "8 hrs/day · seasonal",
        accommodation: "Employer-provided housing",
        accommodationAr: "سكن يوفره صاحب العمل",
      },
      {
        slug: "slovenia-graduate",
        track: "graduate",
        title: "Industrial Work & Graduate Employment",
        titleAr: "عمل صناعي وتوظيف خريجين",
        category: "Manufacturing & Industry",
        categoryAr: "صناعة وتصنيع",
        duration: "12–24 months",
        price: 1750,
        deposit: 204,
        installments: 6,
        expectedSalary: "€1,100–€1,700 / month",
        expectedSalaryAr: "€1,100–€1,700 / شهرياً",
        workingHours: "8 hrs/day · 5 days/week",
        accommodation: "Company housing or allowance",
        accommodationAr: "سكن الشركة أو بدل سكن",
      },
      {
        slug: "slovenia-medical-nursing",
        track: "graduate",
        title: "Nurses & Physician Assistants (Clinical Care)",
        titleAr: "ممرضون ومساعدو أطباء (رعاية سريرية ومستشفيات)",
        category: "Healthcare & Nursing",
        categoryAr: "تمريض ومساعد طبيب",
        duration: "12–24 months",
        price: 1850,
        deposit: 204,
        installments: 6,
        expectedSalary: "€1,300–€2,100 / month",
        expectedSalaryAr: "€1,300–€2,100 / شهرياً",
        workingHours: "40 hrs/week · Shifts",
        accommodation: "Housing allowance provided",
        accommodationAr: "بدل سكن موفر",
        requirements: ["Nursing / Healthcare diploma", "Basic English", "Clean background"],
        requirementsAr: ["مؤهل تمريض أو معهد صحي", "إنجليزية مقبولة", "صحيفة جنائية نظيفة"],
      },
      {
        slug: "slovenia-engineers-specialists",
        track: "graduate",
        title: "Engineers (Civil, Mechanical & Electrical)",
        titleAr: "مهندسون متخصصون (مدني، ميكانيكا، كهرباء)",
        category: "Engineering & Technical",
        categoryAr: "هندسة وتقنية",
        duration: "12–24 months",
        price: 1950,
        deposit: 214,
        installments: 6,
        expectedSalary: "€1,500–€2,500 / month",
        expectedSalaryAr: "€1,500–€2,500 / شهرياً",
        workingHours: "40 hrs/week · Mon–Fri",
        accommodation: "Company housing or allowance",
        accommodationAr: "سكن الشركة أو بدل سكن",
        requirements: ["BSc in Engineering", "1+ yr experience", "Basic English"],
        requirementsAr: ["بكالوريوس هندسة معتمد", "خبرة سنة أو أكثر", "إنجليزية مقبولة"],
      },
    ],
    documents: docs,
    eligibility: ["Age 18–45", "Basic English", "Clean criminal record"],
    timeline: [
      { step: "Application review", time: "3–5 days" },
      { step: "Employer matching & interview", time: "2–4 weeks" },
      { step: "Single permit issuance", time: "4–8 weeks" },
      { step: "Visa & travel", time: "2–3 weeks" },
    ],
  },

  // ─── IRELAND ─────────────────────────────────────────────────────────────────
  {
    slug: "ireland",
    name: "Ireland",
    nameAr: "أيرلندا",
    flag: "🇮🇪",
    image: ireland,
    tagline: "English-speaking careers in Europe's fastest-growing tech hub",
    taglineAr: "مسارات مهنية بالإنجليزية في مركز التقنية الأوروبي الأسرع نمواً",
    description: "Critical skills and general employment permits in one of Europe's strongest job markets, with English as the working language.",
    descriptionAr: "تصاريح عمل للمهارات المطلوبة والوظائف العامة في واحدة من أقوى أسواق العمل في أوروبا، والإنجليزية هي لغة العمل.",
    programs: [
      {
        slug: "ireland-student",
        track: "student",
        title: "Student Pathway & Study in Ireland",
        titleAr: "مسار الطلاب والدراسة في أيرلندا",
        category: "Higher Education",
        categoryAr: "تعليم جامعي",
        duration: "3–6 months",
        price: 2900,
        deposit: 214,
        installments: 6,
        expectedSalary: "Part-time €900–€1,300 / month",
        expectedSalaryAr: "دوام جزئي €900–€1,300 / شهرياً",
        workingHours: "Full-time study + 20 hrs/week",
        accommodation: "Student housing or private",
        accommodationAr: "سكن طلابي أو خاص",
      },
      {
        slug: "ireland-doctors-physicians",
        track: "graduate",
        title: "Medical Doctors & General Practitioners",
        titleAr: "أطباء بشريون وممارسون عامون (مسار الأطباء)",
        category: "Healthcare & Medicine",
        categoryAr: "طب ورعاية صحية",
        duration: "12–24 months",
        price: 3600,
        deposit: 222,
        installments: 6,
        expectedSalary: "€4,500–€7,500 / month",
        expectedSalaryAr: "€4,500–€7,500 / شهرياً",
        workingHours: "40 hrs/week · Hospital / Clinic",
        accommodation: "Relocation allowance & housing assistance",
        accommodationAr: "بدل انتقال ودعم توفير السكن",
        requirements: ["Medical Degree (MBBS / MBBCh)", "Good English (IELTS 6.5+ / OET)", "Registration eligibility"],
        requirementsAr: ["بكالوريوس طب وجراحة معتمد", "إنجليزية جيدة (IELTS 6.5+ أو OET)", "سنة الامتياز أو ترخيص المزاولة"],
      },
      {
        slug: "ireland-registered-nurses",
        track: "graduate",
        title: "Registered Nurses & Clinical Staff",
        titleAr: "ممرضون وممرضات (رعاية سريرية ومستشفيات)",
        category: "Healthcare & Nursing",
        categoryAr: "تمريض ورعاية صحية",
        duration: "12–24 months",
        price: 3300,
        deposit: 214,
        installments: 6,
        expectedSalary: "€2,800–€4,200 / month",
        expectedSalaryAr: "€2,800–€4,200 / شهرياً",
        workingHours: "37.5–40 hrs/week · Shifts",
        accommodation: "Hospital accommodation or housing allowance",
        accommodationAr: "سكن مستشفى أو بدل سكن شهري",
        requirements: ["BSc in Nursing / Health Institute", "1+ yr clinical experience", "Good English"],
        requirementsAr: ["بكالوريوس تمريض أو معهد فني صحي", "خبرة سنة أو أكثر", "إجادة الإنجليزية"],
      },
      {
        slug: "ireland-physician-assistants",
        track: "graduate",
        title: "Physician Assistants & Clinical Technicians",
        titleAr: "مساعد طبيب وفني رعاية طبية",
        category: "Healthcare & Medical Support",
        categoryAr: "مساعد طبيب ورعاية صحية",
        duration: "12–24 months",
        price: 3200,
        deposit: 214,
        installments: 6,
        expectedSalary: "€2,500–€3,800 / month",
        expectedSalaryAr: "€2,500–€3,800 / شهرياً",
        workingHours: "40 hrs/week · Clinic / Medical Center",
        accommodation: "Housing allowance provided",
        accommodationAr: "بدل سكن مشمول",
        requirements: ["Health Sciences Diploma/Degree", "1+ yr clinical/hospital experience", "Intermediate English"],
        requirementsAr: ["مؤهل علوم صحية أو معهد تمريض/مساعد طبيب", "خبرة سنة في عيادة أو مشفى", "إنجليزية متوسطة"],
      },
      {
        slug: "ireland-engineers-specialists",
        track: "graduate",
        title: "Critical Skills Engineers (Civil, Mechanical, Electrical & Tech)",
        titleAr: "مهندسون متخصصون (مدني، ميكانيكا، كهرباء، برمجيات)",
        category: "Engineering & Technology",
        categoryAr: "هندسة وتقنية",
        duration: "12–24 months",
        price: 3500,
        deposit: 222,
        installments: 6,
        expectedSalary: "€3,200–€5,500 / month",
        expectedSalaryAr: "€3,200–€5,500 / شهرياً",
        workingHours: "40 hrs/week · Mon–Fri",
        accommodation: "Relocation package negotiable",
        accommodationAr: "باقة انتقال وبدل سكن",
        requirements: ["BSc in Engineering (Civil, Mechanical, Electrical, Software)", "2+ yrs experience", "Professional English"],
        requirementsAr: ["بكالوريوس هندسة معتمد", "خبرة سنتين أو أكثر في التخصص", "إنجليزية مهنية جيدة"],
      },
      {
        slug: "ireland-graduate",
        track: "graduate",
        title: "Critical Skills Employment Permit",
        titleAr: "تصريح العمل للمهارات الحرجة المطلوبة",
        category: "Professional & Skilled",
        categoryAr: "مهني ومهارات متخصصة",
        duration: "12–24 months",
        price: 3400,
        deposit: 222,
        installments: 6,
        expectedSalary: "€2,800–€5,000 / month",
        expectedSalaryAr: "€2,800–€5,000 / شهرياً",
        workingHours: "40 hrs/week · Mon–Fri",
        accommodation: "Relocation allowance included",
        accommodationAr: "بدل انتقال مشمول",
      },
    ],
    documents: [...docs, "Diplomas & professional degrees"],
    eligibility: ["Age 21–50", "Good English (IELTS 5+ preferred)", "Relevant work experience"],
    timeline: [
      { step: "Profile assessment & CV review", time: "1 week" },
      { step: "Interviews & Job offer", time: "3–6 weeks" },
      { step: "Employment permit processing", time: "6–10 weeks" },
      { step: "Visa & relocation", time: "3–4 weeks" },
    ],
  },
];

export const fromPrice = (c: Country) => Math.min(...c.programs.map((p) => p.price));
export const fromDeposit = (c: Country) => Math.min(...c.programs.map((p) => p.deposit));
export const eur = (n: number) => `€${n.toLocaleString("en-US")}`;
export const getCountry = (slug: string) => countries.find((c) => c.slug === slug);
export const getProgram = (slug: string) => {
  for (const c of countries) {
    const p = c.programs.find((x) => x.slug === slug);
    if (p) return { country: c, program: p };
  }
  return undefined;
};

